package app.enums;

public enum ProcessCommand {
	DO_UNIT_MOVE, 
	CREATE_UNIT_MOVE, 
	COMPLETE_UNIT_MOVE, 
	LOCK_MENU_MOVE_TYPE, 
	CHANGE_MENU_MOVE_TYPE, 
	UNLOCK_MENU_MOVE_TYPE, 
	CHANGE_UNIT_MOVE_TYPE,
	GO_BACK_IN_MOVE_HISTORY, 
	GO_FORWARD_IN_MOVE_HISTORY, 
	PLAY_MOVE_HISTORY_FROM_CURRENT
}
